apiVersion: v1
kind: Service
metadata:
  name: backend-svc1
spec:
  ports:
    - port: 9091
      protocol: TCP
      targetPort: 9090
  selector:
    app: backend
  type: ClusterIP  
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc2
spec:
  type: NodePort
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9090
  selector:
    app: backend 

# kubectl apply -f app-service.yaml 