# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://devopsfti.postgres.database.azure.com/databasename
    username: usernameofdatabase
    password: passwordofdatabase
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 9090
# Security configuration
security:
  user:
    name: user
password: user
